### ISSUE TITLE
Volume Viewer synchronization should be based on world coordinates.

### ISSUE THREAD

**Issue by tsherif** [aces/brainbrowser#15]
I've been told this would be more meaningful than the current setup which syncs based on voxel coordinates.

**Comment by natacha-beck** [comment]
Duplication of issue #209

**Comment by rdvincent** [comment]
@natacha-beck Actually, I think this is a separate issue. #209 refers to the actual registration of the images, this is what I fixed. This issue reflects the fact that when synchronization is selected, the coordinates of the cursor follow the voxel coordinates. I had to enable "Synchronize" button in the NIfTI-1 example to illustrate this (https://github.com/aces/brainbrowser/pull/274). If you choose this option, you'll see that clicking on a location in one image moves the cursor in the other image, but not to the same part of the brain. Since the images are registered in the same world coordinate space, the cursor should move to roughly the same location in the brain (world coordinates).
